// ui
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const OPEN_DISPATCH = "OPEN_DISPATCH";
export const STOP_DISPATCH = "STOP_DISPATCH";
export const LOADING_COMMENT = "LOADING_COMMENT";
export const STOP_LOADING_COMMENT = "STOP_LOADING_COMMENT";

// Users
export const SET_USER = "SET_USER";
export const LOG_OUT = "LOG_OUT";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";

// scream
export const POST_SCREAM = "POST_SCREAM";
export const DELETE_SCREAM = "DELETE_SCREAM";
export const LOADING_SCREAMS = "LOADING_SCREAM";
export const GET_ALL_SCREAM_FIRST = "GET_ALL_SCREAM_FIRST";
export const GET_ALL_SCREAM_PAGNATION = "GET_ALL_SCREAM_PAGNATION";
export const GET_ONE_SCREAM = "GET_ONE_SCREAM";
export const POST_COMMENT = "POST_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const LIKE_SCREAM = "LIKE_SCREAM";
export const UNLIKE_SCREAM = "UNLIKE_SCREAM";
